# Generated by Django 4.2.4 on 2023-09-11 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ratingAuthor", models.SmallIntegerField(default=0)),
                (
                    "authorUser",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("dateCreation", models.DateTimeField(auto_now_add=True)),
                ("rating", models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoryType",
                    models.CharField(
                        choices=[("NW", "Новость"), ("AR", "Статья")],
                        default="AR",
                        max_length=2,
                    ),
                ),
                ("dateCreation", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=128)),
                ("text", models.TextField()),
                ("rating", models.SmallIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.author"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.DeleteModel(
            name="News",
        ),
        migrations.AddField(
            model_name="postcategory",
            name="categoryThrough",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="news.category"
            ),
        ),
        migrations.AddField(
            model_name="postcategory",
            name="postThrough",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="news.post"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="postCategory",
            field=models.ManyToManyField(
                through="news.PostCategory", to="news.category"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="commentPost",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="news.post"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="commentUser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
